name: Create new rtl_433 addon release

on:
  push:
    branches:
      - next
    tags:
      - '2*'
  schedule:
    # A random daily time, as Actions doesn't have a suggestion for running
    # daily without causing job spikes.
    - cron: '16 8 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release Build
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/build-addon.yml
    with:
      build-type: release

  nightly:
    name: Nightly Build
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/build-addon.yml
    with:
      build-type: nightly
      checkout-ref: next
      skip-tag-check: true
